# Generated by Django 3.2.15 on 2022-08-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_incident'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='time_complete_hr',
            new_name='time_completion_hr',
        ),
    ]
